application: helloworld
version: 1
runtime: php55
api_version: 1

handlers:
# Serve the stylesheets
- url: /css
  static_dir: css
  
# Serve the images
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
    
# Serve the less files
- url: /less
  static_dir: less
  
# Serve the JavaScript files
- url: /js
  static_dir: js
  
# Serve the FontAwesome files
- url: /font-awesome
  static_dir: font-awesome
  
# Serve the font files
- url: /fonts
  static_dir: fonts
  
- url: /.*
  script: index.html
  
